const ADD_PRODUCT = "ADD_PRODUCT";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

const PRODUCTS_DOWNLOAD_START = "PRODUCTS_DOWNLOAD_START";
const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS";
const PRODUCTS_DOWNLOAD_FAILURE = "PRODUCTS_DOWNLOAD_FAILURE";

const PRODUCT_DELETE_GET = "PRODUCT_DELETE_GET";
const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";

const PRODUCT_EDIT_GET = "PRODUCT_EDIT_GET";
const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
const PRODUCT_EDIT_FAILURE = "PRODUCT_EDIT_FAILURE";

export const actionTypes = {
    ADD_PRODUCT,
    ADD_PRODUCT_SUCCESS,
    ADD_PRODUCT_FAILURE,
    PRODUCTS_DOWNLOAD_START,
    PRODUCTS_DOWNLOAD_SUCCESS,
    PRODUCTS_DOWNLOAD_FAILURE,
    PRODUCT_DELETE_GET,
    PRODUCT_DELETE_SUCCESS,
    PRODUCT_DELETE_FAILURE,
    PRODUCT_EDIT_GET,
    PRODUCT_EDIT_SUCCESS,
    PRODUCT_EDIT_FAILURE
}