export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE"

export const PRODUCTS_DOWNLOAD_START = "PRODUCTS_DOWNLOAD_START"
export const PRODUCTS_DOWNLOAD_SUCCESS = "PRODUCTS_DOWNLOAD_SUCCESS"
export const PRODUCTS_DOWNLOAD_FAILURE = "PRODUCTS_DOWNLOAD_FAILURE"